name: wallpaper
description: "A new Flutter project."

publish_to: 'none' # Keeps the package private

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensures compatibility with Dart 3+

dependencies:
  flutter:
    sdk: flutter
  
  # Essential UI Libraries
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.0
  firebase_core: ^3.10.1 
  cloud_firestore: ^5.6.2 
  firebase_storage: ^12.4.1
  random_string: ^2.3.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Optional Plugins for App Enhancement (Comment out if not needed)
# Run `flutter pub run flutter_launcher_icons:main` to generate app icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"

# Run `flutter pub run flutter_native_splash:create` to generate splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/splash.png
